### ISSUE TITLE
create new repos for UCS agent and logstash plugin

### ISSUE THREAD

**Issue by jwbcisco** [CiscoZeus/zeus-ingestion-plugins#10]
@marcsolanas per our discussion, please create separate repos for ucs agent and logstash plugin. Thanks.

**Comment by marcsolanas** [comment]
Please lets include a Creative commons 2 license file in each repo.

@yoelcabo @muzixing 

https://github.com/CiscoZeus/zeus-ucs-agent
https://github.com/CiscoZeus/logstash-output-CiscoZeus

**Comment by marcsolanas** [comment]
Forget abou tthe license thing. Apache is the correct one. my mistake.

**Comment by yoelcabo** [comment]
@marcsolanas let's do that: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/ so that we keep the commit history :)
(I can do it if you give me access)

**Comment by marcsolanas** [comment]
@yoelcabo you should now have access.

**Comment by yoelcabo** [comment]
@jwbcisco @marcsolanas I just moved the logstash plugin.

I was going to do the same with the UCS one but apparently @muzixing has already put content there.

The content is essentially the same (I just run a `diff`).

Closing this issue therefore.
