### ISSUE TITLE
use "place holder" IP, user name, password, token in config.py

### ISSUE THREAD

**Issue by jwbcisco** [CiscoZeus/zeus-ingestion-plugins#11]
We should not have actual token, IP, username or password in the config file. instead use:

 UCS = <UCS Manager IP address in single quotes>
  UCS_USER = <UCS Manager user name in single quotes>
  UCS_PASSWD = <UCS Manager password in single quotes>
  IS_SECURE = True
  PORT = 443
  LOG_LEVEL = 'INFO'
  
  ZEUS_TOKEN = <Zeus token in double quotes>
  ZEUS_SERVER = <Zeus API URL in double quotes>

**Comment by jwbcisco** [comment]
Hmm. Github took away what I put in angle brackets in view mode but it reappears in edit mode:  here is a screen shot just in case
<img width="470" alt="screen shot 2017-03-29 at 11 21 49 am" src="https://cloud.githubusercontent.com/assets/16708222/24469914/f7fba5f2-1471-11e7-97e6-1f4d0b1ea0f0.png">

**Comment by muzixing** [comment]
OK

**Comment by muzixing** [comment]
done
