### ISSUE TITLE
change reference to "plugin" in init description

### ISSUE THREAD

**Issue by jwbcisco** [CiscoZeus/zeus-ingestion-plugins#9]
@muzixing You skipped one change:
![change to agent](https://cloud.githubusercontent.com/assets/16708222/24375226/6f8a8d4a-12ec-11e7-8341-b0d56b796dfb.png)

**Comment by muzixing** [comment]
oh yes!! commit info!

**Comment by jwbcisco** [comment]
Cheng fixed
